-- MySQL Script generated by MySQL Workbench
-- Sun Oct 12 20:32:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nombreCargo` VARCHAR(100) NULL,
  `descripcionCargo` TEXT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(255) NULL,
  `ultimaConexion` TIMESTAMP NULL,
  `estadoUsuario` TINYINT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `apellidoPaterno` VARCHAR(100) NULL,
  `apellidoMaterno` VARCHAR(100) NULL,
  `rut` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Cargo_idCargo`, `Usuario_idUsuario`),
  INDEX `fk_Empleado_Cargo_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Empleado_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Cargo`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MarcaVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MarcaVehiculo` (
  `idMarcaVehiculo` INT NOT NULL,
  `nombreMarca` VARCHAR(45) NULL,
  PRIMARY KEY (`idMarcaVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModeloVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModeloVehiculo` (
  `idModeloVehiculo` INT NOT NULL,
  `nombreModelo` VARCHAR(45) NULL,
  `anioModelo` INT NULL,
  `MarcaVehiculo_idMarcaVehiculo` INT NOT NULL,
  PRIMARY KEY (`idModeloVehiculo`, `MarcaVehiculo_idMarcaVehiculo`),
  INDEX `fk_ModeloVehiculo_MarcaVehiculo1_idx` (`MarcaVehiculo_idMarcaVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_ModeloVehiculo_MarcaVehiculo1`
    FOREIGN KEY (`MarcaVehiculo_idMarcaVehiculo`)
    REFERENCES `mydb`.`MarcaVehiculo` (`idMarcaVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoVehiculo` (
  `idTipoVehiculo` INT NOT NULL,
  `tipoVehiculo` VARCHAR(45) NULL,
  `descripcionTipoVehiculo` TEXT NULL,
  PRIMARY KEY (`idTipoVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `nombreSucursal` VARCHAR(100) NULL,
  `direccionSucursal` VARCHAR(200) NULL,
  `regionSucursal` VARCHAR(45) NULL,
  `comunaSucursal` VARCHAR(45) NULL,
  `telefonoSucursal` VARCHAR(45) NULL,
  `emailSucursal` VARCHAR(100) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `idVehiculo` INT NOT NULL,
  `patenteVehiculo` VARCHAR(45) NULL,
  `anioVehiculo` INT NULL,
  `fechaAdquisicionVehiculo` DATE NULL,
  `capacidadCargaVehiculo` DECIMAL NULL,
  `estadoVehiculo` VARCHAR(45) NULL,
  `kilometrajeVehiculo` VARCHAR(45) NULL,
  `ModeloVehiculo_idModeloVehiculo` INT NOT NULL,
  `ModeloVehiculo_MarcaVehiculo_idMarcaVehiculo` INT NOT NULL,
  `TipoVehiculo_idTipoVehiculo` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idVehiculo`, `ModeloVehiculo_idModeloVehiculo`, `ModeloVehiculo_MarcaVehiculo_idMarcaVehiculo`, `TipoVehiculo_idTipoVehiculo`, `Sucursal_idSucursal`),
  INDEX `fk_Vehiculo_ModeloVehiculo1_idx` (`ModeloVehiculo_idModeloVehiculo` ASC, `ModeloVehiculo_MarcaVehiculo_idMarcaVehiculo` ASC) VISIBLE,
  INDEX `fk_Vehiculo_TipoVehiculo1_idx` (`TipoVehiculo_idTipoVehiculo` ASC) VISIBLE,
  INDEX `fk_Vehiculo_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  UNIQUE INDEX `patente_UNIQUE` (`patenteVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_ModeloVehiculo1`
    FOREIGN KEY (`ModeloVehiculo_idModeloVehiculo` , `ModeloVehiculo_MarcaVehiculo_idMarcaVehiculo`)
    REFERENCES `mydb`.`ModeloVehiculo` (`idModeloVehiculo` , `MarcaVehiculo_idMarcaVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_TipoVehiculo1`
    FOREIGN KEY (`TipoVehiculo_idTipoVehiculo`)
    REFERENCES `mydb`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acceso` (
  `idAcceso` INT NOT NULL,
  `fechaIngreso` TIMESTAMP NULL,
  `fechaSalida` TIMESTAMP NULL,
  `observaciones` VARCHAR(200) NULL,
  `imagenUrl` VARCHAR(200) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Empleado_Cargo_idCargo` INT NOT NULL,
  `Empleado_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAcceso`, `Empleado_idEmpleado`, `Empleado_Cargo_idCargo`, `Empleado_Usuario_idUsuario`),
  INDEX `fk_Acceso_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Cargo_idCargo` ASC, `Empleado_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Acceso_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Cargo_idCargo` , `Empleado_Usuario_idUsuario`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado` , `Cargo_idCargo` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenTrabajo` (
  `idOrdenTrabajo` INT NOT NULL,
  `fechaInicioOT` TIMESTAMP NULL,
  `fechaCierreOT` TIMESTAMP NULL,
  `descripcionOT` TEXT NULL,
  `estadoOT` VARCHAR(45) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Empleado_Cargo_idCargo` INT NOT NULL,
  `Vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idOrdenTrabajo`, `Empleado_idEmpleado`, `Empleado_Cargo_idCargo`, `Vehiculo_idVehiculo`),
  INDEX `fk_OrdenTrabajo_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_OrdenTrabajo_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_OrdenTrabajo_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Cargo_idCargo`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado` , `Cargo_idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Llaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Llaves` (
  `idLlaves` INT NOT NULL,
  `fechaPrestamoLlaves` DATE NULL,
  `fechaDevolucionLlaves` DATE NULL,
  `observacionesLlaves` VARCHAR(200) NULL,
  `Vehiculo_idVehiculo` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Empleado_Cargo_idCargo` INT NOT NULL,
  `Empleado_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLlaves`, `Vehiculo_idVehiculo`, `Empleado_idEmpleado`, `Empleado_Cargo_idCargo`, `Empleado_Usuario_idUsuario`),
  INDEX `fk_Llaves_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_Llaves_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Cargo_idCargo` ASC, `Empleado_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Llaves_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llaves_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Cargo_idCargo` , `Empleado_Usuario_idUsuario`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado` , `Cargo_idCargo` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL,
  `nombreServicio` VARCHAR(45) NULL,
  `descripcionServicio` VARCHAR(200) NULL,
  `OrdenTrabajo_idOrdenTrabajo` INT NOT NULL,
  `OrdenTrabajo_Empleado_idEmpleado` INT NOT NULL,
  `OrdenTrabajo_Empleado_Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `OrdenTrabajo_idOrdenTrabajo`, `OrdenTrabajo_Empleado_idEmpleado`, `OrdenTrabajo_Empleado_Cargo_idCargo`),
  INDEX `fk_Servicio_OrdenTrabajo1_idx` (`OrdenTrabajo_idOrdenTrabajo` ASC, `OrdenTrabajo_Empleado_idEmpleado` ASC, `OrdenTrabajo_Empleado_Cargo_idCargo` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_OrdenTrabajo1`
    FOREIGN KEY (`OrdenTrabajo_idOrdenTrabajo` , `OrdenTrabajo_Empleado_idEmpleado` , `OrdenTrabajo_Empleado_Cargo_idCargo`)
    REFERENCES `mydb`.`OrdenTrabajo` (`idOrdenTrabajo` , `Empleado_idEmpleado` , `Empleado_Cargo_idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Repuesto` (
  `idRepuesto` INT NOT NULL,
  `nombreRepuesto` VARCHAR(45) NULL,
  `descripcionRepuesto` TEXT NULL,
  `stockRepuesto` INT NULL,
  PRIMARY KEY (`idRepuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OTRepuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OTRepuesto` (
  `idOTRepuesto` INT NOT NULL,
  `cantidadOTRepuesto` INT NULL,
  `OrdenTrabajo_idOrdenTrabajo` INT NOT NULL,
  `OrdenTrabajo_Empleado_idEmpleado` INT NOT NULL,
  `OrdenTrabajo_Empleado_Cargo_idCargo` INT NOT NULL,
  `OrdenTrabajo_Vehiculo_idVehiculo` INT NOT NULL,
  `Repuesto_idRepuesto` INT NOT NULL,
  PRIMARY KEY (`idOTRepuesto`, `OrdenTrabajo_idOrdenTrabajo`, `OrdenTrabajo_Empleado_idEmpleado`, `OrdenTrabajo_Empleado_Cargo_idCargo`, `OrdenTrabajo_Vehiculo_idVehiculo`, `Repuesto_idRepuesto`),
  INDEX `fk_OTRepuesto_OrdenTrabajo1_idx` (`OrdenTrabajo_idOrdenTrabajo` ASC, `OrdenTrabajo_Empleado_idEmpleado` ASC, `OrdenTrabajo_Empleado_Cargo_idCargo` ASC, `OrdenTrabajo_Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_OTRepuesto_Repuesto1_idx` (`Repuesto_idRepuesto` ASC) VISIBLE,
  CONSTRAINT `fk_OTRepuesto_OrdenTrabajo1`
    FOREIGN KEY (`OrdenTrabajo_idOrdenTrabajo` , `OrdenTrabajo_Empleado_idEmpleado` , `OrdenTrabajo_Empleado_Cargo_idCargo` , `OrdenTrabajo_Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`OrdenTrabajo` (`idOrdenTrabajo` , `Empleado_idEmpleado` , `Empleado_Cargo_idCargo` , `Vehiculo_idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OTRepuesto_Repuesto1`
    FOREIGN KEY (`Repuesto_idRepuesto`)
    REFERENCES `mydb`.`Repuesto` (`idRepuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Incidencia` (
  `idIncidencia` INT NOT NULL,
  `fechaIncidencia` TIMESTAMP NULL,
  `descripcionIncidencia` TEXT NULL,
  `estadoIncidencia` VARCHAR(45) NULL,
  `gravedadIncidencia` VARCHAR(45) NULL,
  `observacionesIncidencia` TEXT NULL,
  `OrdenTrabajo_idOrdenTrabajo` INT NOT NULL,
  `OrdenTrabajo_Empleado_idEmpleado` INT NOT NULL,
  `OrdenTrabajo_Empleado_Cargo_idCargo` INT NOT NULL,
  `OrdenTrabajo_Vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idIncidencia`, `OrdenTrabajo_idOrdenTrabajo`, `OrdenTrabajo_Empleado_idEmpleado`, `OrdenTrabajo_Empleado_Cargo_idCargo`, `OrdenTrabajo_Vehiculo_idVehiculo`),
  INDEX `fk_Incidencia_OrdenTrabajo1_idx` (`OrdenTrabajo_idOrdenTrabajo` ASC, `OrdenTrabajo_Empleado_idEmpleado` ASC, `OrdenTrabajo_Empleado_Cargo_idCargo` ASC, `OrdenTrabajo_Vehiculo_idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Incidencia_OrdenTrabajo1`
    FOREIGN KEY (`OrdenTrabajo_idOrdenTrabajo` , `OrdenTrabajo_Empleado_idEmpleado` , `OrdenTrabajo_Empleado_Cargo_idCargo` , `OrdenTrabajo_Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`OrdenTrabajo` (`idOrdenTrabajo` , `Empleado_idEmpleado` , `Empleado_Cargo_idCargo` , `Vehiculo_idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
